version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  sample:
    jobs:
      - build-and-test


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Python upgrade
          command: python3.8 -m pip install --upgrade pip
      - run:
          name: Run tests
          command: coverage run --source=geo_calculator -m pytest && coverage json
