name: geo-calculator

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run:
        python -m pip install --upgrade pip &&
        pip install omni-coveragereporter==0.0.0 &&
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi &&
        pip3 install coverage &&
        pip3 install pytest &&
        pip3 install GitPython &&
        pip3 install requests
    - name: Generate Reports
      run: coverage run --source=geo_calculator -m pytest && coverage json
    - name: Send reports
      run: omni_coveragereporter_python.py
      env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
         CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
